esphome:
  name: testnode
  friendly_name: testnode

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
    
ota:
  - platform: esphome

wifi:
  ssid: HowarthWifi
  password: heyes358
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 10.248.100.237
    # Set this to the IP address of the router. Often ends with .1
    gateway: 10.248.100.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testnode Fallback Hotspot"
    password: "Mp8L7lepu3dU"

captive_portal:
    