esphome:
  name: wroom-test
  friendly_name: wroom-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KgpDrXcg9qVK/Qn8TQPg0QQJzAuxMJfVYtDFDwnkTlU="

ota:
  - platform: esphome
    password: "4e62c5f544720a26bce229621cca9ff1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wroom-Test Fallback Hotspot"
    password: "zFMN78lDhSXa"

captive_portal:
    